file:
  tree: '/workspaces/Ms2z/mnt/data/graph/test_10k/tensor/tensor.pt'
  # fp: '/workspaces/Ms2z/mnt/data/graph/pubchem_10k/tensor/fp_tensors.pt'
  vocab_file: '/workspaces/Ms2z/mnt/data/graph/test_10k/vocab.pkl'

train: 
  device: cuda
  batch_size: 16
  epochs: 1000

  optimizer:
    name: Adam
    lr: 0.0001
    eps: !!float 1e-8
  # load_name: ckptest1217
  load_name: null
  load_epoch: null # 0 or null for no load, 1 for load from epoch 1, -1 for load from last epoch
  load_iter: null # null for no load, 100 for load from iter 100, -1 for load from last iter
  train_size: 0.8
  val_size: 0.1
  test_size: 0.1
  save_epoch: 1000000
  save_iter: null

model:
  node_dim: 256
  edge_dim: 8
  latent_dim: 512
  decoder_layers: 2
  decoder_heads: 4
  decoder_ff_dim: 512
  decoder_dropout: 0.1



  